//! The line-shaped diagrams in `docs/method.md`, generated by the tool itself.
//!
//! Spec 9.3: the document and the renderer share one visual language, so the
//! diagrams that depict real line states are produced by the same code that
//! draws the ribbon. The document cannot drift from the tool's output because
//! the output *is* the document.

use crate::config::Config;
use crate::format::parse;
use crate::glyphs::{Glyphs, Mode};
use crate::model::{Id, Line, Ref};
use crate::tui::ribbon::{build, plain};
use crate::view;

/// The seven line-shaped diagrams from spec 9.2.
pub const NAMES: [&str; 7] = [
    "the-line",
    "sliding-window",
    "selected-slice",
    "landmark-not-bucket",
    "history-months",
    "markers-after-launch",
    "window-is-a-view",
];

fn fixture(past: &[&str], future: &[&str], markers: &[(usize, &str)]) -> Line {
    let mut src = String::from("# Diagram\n\n");
    for (n, t) in past.iter().enumerate() {
        src.push_str(&format!("- [x] {t}  ^p{n}\n"));
    }
    src.push_str("\n── NOW ──\n\n");
    for (n, t) in future.iter().enumerate() {
        if let Some((_, label)) = markers.iter().find(|(at, _)| *at == n) {
            src.push_str(&format!("\n◆ {label} ◆\n\n"));
        }
        src.push_str(&format!("- [ ] {t}  ^f{n}\n"));
    }
    parse(&src).expect("diagram fixtures must parse")
}

fn wide() -> Config {
    // Diagrams are not terminal-constrained, so never elide.
    Config::default()
}

fn ribbon(line: &Line, cfg: &Config) -> String {
    let w = view::window(line, cfg);
    plain(&build(line, w, &Glyphs::for_mode(Mode::Unicode), 400))
}

fn no_window(line: &Line) -> String {
    // A span outside the line draws no bracket, for diagrams about the line
    // itself rather than about attention.
    let span = view::Span {
        start: usize::MAX,
        end: usize::MAX,
    };
    plain(&build(line, span, &Glyphs::for_mode(Mode::Unicode), 400))
}

/// Widen the rule between entries so labels have room to sit beneath them.
/// The ribbon is dense by design — two columns per item — which is right on a
/// terminal but too tight for prose labels in a document.
fn widen(ribbon: &str, n: usize) -> String {
    ribbon
        .chars()
        .map(|c| {
            if c == '\u{2500}' {
                "\u{2500}".repeat(n)
            } else {
                c.to_string()
            }
        })
        .collect()
}

/// Column of the first occurrence of `needle` in a rendered ribbon.
fn col_of(ribbon: &str, needle: char) -> usize {
    ribbon.chars().position(|c| c == needle).unwrap_or(0)
}

/// Columns of every item glyph, left to right.
fn item_cols(ribbon: &str) -> Vec<usize> {
    ribbon
        .chars()
        .enumerate()
        .filter(|(_, c)| *c == '\u{25cf}' || *c == '\u{25cb}')
        .map(|(i, _)| i)
        .collect()
}

/// Place labels at exact columns beneath a ribbon. Labels are positioned from
/// the rendered output rather than guessed, so they cannot drift out of
/// alignment when the fixtures or glyphs change.
fn labels(pairs: &[(usize, &str)]) -> String {
    let mut row = String::new();
    for (col, text) in pairs {
        while row.chars().count() < *col {
            row.push(' ');
        }
        row.push_str(text);
    }
    row
}

pub fn render(name: &str) -> Option<String> {
    let cfg = wide();
    Some(match name {
        "the-line" => {
            let l = fixture(&["a", "b", "c", "d"], &["e", "f", "g", "h"], &[]);
            let r = widen(&no_window(&l), 3);
            let now = col_of(&r, '\u{2502}');
            let end = r.chars().count();
            let head = labels(&[
                (0, "PAST"),
                (now.saturating_sub(1), "NOW"),
                (end.saturating_sub(6), "FUTURE"),
            ]);
            format!("{head}\n{r}\n")
        }
        "sliding-window" => {
            let l = fixture(&["a", "b", "c", "d"], &["e", "f", "g", "h", "i"], &[]);
            format!("{}\n        the window moves forward\n", ribbon(&l, &cfg))
        }
        "selected-slice" => {
            let l = fixture(&["a", "b", "c", "d", "e"], &["f", "g"], &[]);
            let s = view::slice(&l, &Ref::Id(Id::new("p1")), &Ref::Id(Id::new("p3")))?;
            format!(
                "{}\n     a slice answers: what happened here?\n",
                plain(&build(&l, s, &Glyphs::for_mode(Mode::Unicode), 400))
            )
        }
        "landmark-not-bucket" | "markers-after-launch" => {
            let l = fixture(&["a", "b"], &["c", "d", "e", "f"], &[(2, "launch")]);
            let r = widen(&no_window(&l), 3);
            let mark = col_of(&r, '\u{25c6}');
            format!(
                "{r}\n{}\n{}\n",
                labels(&[(mark, "\u{2514}\u{2500} work after launch is a PLACE,")]),
                labels(&[(mark + 3, "not a bucket")]),
            )
        }
        "history-months" => {
            let l = fixture(
                &["discovery", "prototype", "experiment"],
                &["release", "learn"],
                &[],
            );
            let r = widen(&no_window(&l), 3);
            let cols = item_cols(&r);
            let months = ["JAN", "FEB", "MAR", "APR", "MAY"];
            let head = labels(
                &cols
                    .iter()
                    .zip(months)
                    // Left-align under each glyph. Centring with a -1 shift
                    // clamps at column 0 for the first label and collides it
                    // with the second.
                    .map(|(c, m)| (*c, m))
                    .collect::<Vec<_>>(),
            );
            format!("{head}\n{r}\n")
        }
        "window-is-a-view" => {
            let l = fixture(&["a", "b", "c", "d", "e", "f"], &["g", "h", "i", "j"], &[]);
            let back = view::slice(&l, &Ref::Id(Id::new("p0")), &Ref::Id(Id::new("p2")))?;
            let fwd = view::slice(&l, &Ref::Id(Id::new("f1")), &Ref::Id(Id::new("f3")))?;
            format!(
                "reviewing March:\n{}\n\nplanning Q3:\n{}\n\n     one line, two readers, no copies\n",
                plain(&build(&l, back, &Glyphs::for_mode(Mode::Unicode), 400)),
                plain(&build(&l, fwd, &Glyphs::for_mode(Mode::Unicode), 400)),
            )
        }
        _ => return None,
    })
}

/// Every generated diagram, wrapped in fenced blocks with a provenance comment
/// so the next reader knows not to hand-edit them.
pub fn render_all() -> String {
    let mut out = String::new();
    for name in NAMES {
        out.push_str(&format!(
            "<!-- diagram: {name} -->\n```\n{}```\n\n",
            render(name).expect("every NAME must render")
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_named_diagram_renders_a_line() {
        for name in NAMES {
            let out = render(name).unwrap_or_else(|| panic!("{name} rendered nothing"));
            assert!(
                out.contains('│') || out.contains('●') || out.contains('○'),
                "{name} does not look like a line: {out}"
            );
        }
    }

    #[test]
    fn diagrams_use_the_unicode_glyph_set_not_ascii() {
        let out = render("the-line").unwrap();
        assert!(
            !out.contains("[x]"),
            "diagrams must be unicode, not ascii (spec 9.3)"
        );
    }

    #[test]
    fn an_unknown_diagram_name_is_none() {
        assert!(render("nope").is_none());
    }

    #[test]
    fn the_window_diagrams_draw_a_bracket_and_the_others_do_not() {
        assert!(render("sliding-window").unwrap().contains('┌'));
        assert!(!render("the-line").unwrap().contains('┌'));
    }
}
